### ISSUE TITLE
Usage from pre-commit

### ISSUE THREAD

**Issue by henryiii** [ssciwr/clang-format-wheel#8]
Currently, this works perfectly like this:

```yaml
- id: clang-format
  name: Clang Format
  language: python
  types:
  - c++
  entry: clang-format
  additional_dependencies: [clang-format==12.*]
  args:
  - -style=file
  - -i
```

However, this will not get update PRs from pre-commit.ci, or support `pre-commit autoupdate`. Ideally, it would be nice to have a hook repository for this. The "obvious" thing, adding a `.pre-commit-hooks.yml` to this repository, would not work, since it will try to build from source. The ideal thing is likely to follow the method used by https://github.com/cheshirekow/cmake-format-precommit, and have a clang-format-precommit repository. It would be very simple, but would require a bit of maintenance every time there's a new release (update a line, make a tag/release). Would you be interested if I set up such a repository and then moved it here? Or I could set this up elsewhere (like in pybind).

**Comment by henryiii** [comment]
`.pre-commit-hooks.yaml`
```yaml
- id: clang-format
  name: clang-format
  description: clang-format your C++ code
  entry: clang-format
  args: [-style=file, -i]
  language: python
  types: [c++]
```

`setup.py`
```python
from setuptools import setup
setup(
    name="clang-format-precommit-dummy",
    version="0.0.0",
    install_requires=["clang-format==12.0.1"]
```

(Could also use setup.cfg + pyproject.toml, or pyproject.toml via flit). The only thing to update on this repo would be the pinned version of clang-format, which would need to match the tag.
