### ISSUE TITLE
How to run on all files in a repository?

### ISSUE THREAD

**Issue by Avasam** [ssciwr/clang-format-wheel#96]
The pre-commit configuration works fine:
```yaml
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v18.1.2"
    hooks:
      - id: clang-format
        # Supports a lot more filetypes, but only tagging those we use
        # https://github.com/pre-commit/mirrors-clang-format/blob/main/.pre-commit-hooks.yaml#L6
        types: [c++, c]
```
`pre-commit run --all`

But I'd like to have this as a github action as well. Running locally, I try `pipx run clang-format -i --dry-run **/*.h **/*.cpp` and it gives the following output:
```
⚠️  clang-format is already on your PATH and installed at C:\Program Files\Python39\Scripts\clang-format.EXE. Downloading and running anyway.
invalid argument
invalid argument
```
